services:
  aisens:
    image: adharmireddi/aisens:V1
    container_name: aisens
    restart: unless-stopped
    ports:
      - "${OPEN_WEBUI_PORT-3000}:8080"
    environment:
      - WEBUI_SECRET_KEY=
      # disable ollama
      - OLLAMA_BASE_URL=
      # optional: enable groq key if you want
      # - GROQ_API_KEY=your_key_here
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  open-webui: {}

